version: '3.8'

services:
  app:
    build: .
    container_name: node-app
    volumes:
      - .:/app
    ports:
      - "8080:8080"  # Map port 8080 of the container to port 8080 on the host
    environment:
      - NODE_ENV=production
    restart: always
