version: '3.8'

services:
  app:
    build: .
    container_name: node-app
    volumes:
      - .:/app
    ports:
      - "8080:8080"  
    environment:
      - NODE_ENV=production
    restart: always
