version: '3.8'

services:
  app:
    build: .
    container_name: node-app
    volumes:
      - .:/app
    ports:
      - "3000:3000"  # Map port 3000 of the container to port 3000 on the host
    environment:
      - NODE_ENV=production
    restart: always
